# Generated by Django 5.1.2 on 2024-10-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='test',
        ),
    ]
